#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Removed index by file id, added indices by community and community + file key."""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1777209602"
down_revision = "dfbc96c5211f"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("uidx_communities_files_id_key"), table_name="communities_files")
    op.create_index(
        op.f("ix_communities_files_record_id"),
        "communities_files",
        ["record_id"],
        unique=False,
    )
    op.create_index(
        "uidx_communities_files_record_id_key",
        "communities_files",
        ["record_id", "key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uidx_communities_files_record_id_key", table_name="communities_files"
    )
    op.drop_index(
        op.f("ix_communities_files_record_id"), table_name="communities_files"
    )
    op.create_index(
        op.f("uidx_communities_files_id_key"),
        "communities_files",
        ["id", "key"],
        unique=True,
    )
    # ### end Alembic commands ###
