# SPDX-FileCopyrightText: 2016-2018 CERN.
# SPDX-FileCopyrightText: 2026 CESNET z.s.p.o.
# SPDX-FileCopyrightText: 2026 Graz University of Technology.
# SPDX-License-Identifier: MIT

"""Removed index by file id, added indices by community and community + file key."""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1777209602"
down_revision = "dfbc96c5211f"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uidx_communities_files_id_key"),
        table_name="communities_files",
        if_exists=True,
    )
    op.create_index(
        op.f("ix_communities_files_record_id"),
        "communities_files",
        ["record_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "uidx_communities_files_record_id_key",
        "communities_files",
        ["record_id", "key"],
        unique=True,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uidx_communities_files_record_id_key",
        table_name="communities_files",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_communities_files_record_id"),
        table_name="communities_files",
        if_exists=True,
    )
    op.create_index(
        op.f("uidx_communities_files_id_key"),
        "communities_files",
        ["id", "key"],
        unique=True,
        if_not_exists=True,
    )
    # ### end Alembic commands ###
